services:
  idrac7:
    build:
      context: .
    image: docker-idrac7
    restart: unless-stopped
    ports:
      - "5800:5800"
      - "5900:5900"
    environment:
      IDRAC_HOST: ${IDRAC_HOST:-idrac7.example.org}
      IDRAC_PORT: ${IDRAC_PORT:-443}
      IDRAC_USER: ${IDRAC_USER:-root}
      IDRAC_PASSWORD: ${IDRAC_PASSWORD:-changeme}
      IDRAC_BYPASS_CERT_JNI: "${IDRAC_BYPASS_CERT_JNI:-true}"
      # Optional:
      # IDRAC_KEYCODE_HACK: "true"
      # VIRTUAL_MEDIA: installer.iso
      # VIRTUAL_MEDIA_START_DELAY: 15
    volumes:
      - ./data/app:/app
      - ./data/vmedia:/vmedia
      - ./data/screenshots:/screenshots

  idrac7-secret:
    profiles: ["secret"]
    build:
      context: .
    image: docker-idrac7
    restart: unless-stopped
    ports:
      - "5801:5800"
      - "5901:5900"
    environment:
      IDRAC_PORT: ${IDRAC_PORT:-443}
      IDRAC_BYPASS_CERT_JNI: "${IDRAC_BYPASS_CERT_JNI:-true}"
    secrets:
      - idrac_host
      - idrac_user
      - idrac_password
    volumes:
      - ./data/app-secret:/app
      - ./data/vmedia:/vmedia
      - ./data/screenshots-secret:/screenshots

secrets:
  idrac_host:
    file: ./secrets/idrac_host.txt
  idrac_user:
    file: ./secrets/idrac_user.txt
  idrac_password:
    file: ./secrets/idrac_password.txt
